import type { z } from 'zod';

import type { AIProvider, AIRequest } from '../../../domain/ai/ai-provider.js';
import type { AIProviderResult } from '../../../domain/ai/ai-provider-result.js';
import {
  AIProviderUnavailableError,
  AIPermanentError,
  AITimeoutError,
  AIValidationError
} from '../../../domain/ai/ai-provider-error.js';
import { WorkerCancelledError } from '../../../domain/workers/worker-errors.js';

export type MockProviderMode =
  | 'success'
  | 'retryable-failure'
  | 'permanent-failure'
  | 'timeout'
  | 'malformed-output';

export type MockProviderDependencies = {
  readonly mode: MockProviderMode;
  readonly now: () => Date;
};

function deterministicUsage(prompt: string): {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  estimatedCostUsd: null;
  latencyMs: number;
} {
  const inputTokens = Math.max(1, Math.floor(prompt.length / 4));
  const outputTokens = 80;
  const totalTokens = inputTokens + outputTokens;

  if (!Number.isSafeInteger(inputTokens) || inputTokens < 0) {
    throw new AIValidationError('Mock provider generated invalid input token usage.', {
      field: 'inputTokens'
    });
  }

  if (!Number.isSafeInteger(outputTokens) || outputTokens < 0) {
    throw new AIValidationError('Mock provider generated invalid output token usage.', {
      field: 'outputTokens'
    });
  }

  if (!Number.isSafeInteger(totalTokens) || totalTokens < 0) {
    throw new AIValidationError('Mock provider token usage overflowed safe integer range.', {
      field: 'totalTokens'
    });
  }

  return {
    inputTokens,
    outputTokens,
    totalTokens,
    estimatedCostUsd: null,
    latencyMs: 5
  };
}

function buildMockPayload(promptKey: string): unknown {
  switch (promptKey) {
    case 'metadata':
      return {
        title: 'Deterministic Transcript Title',
        description: 'Deterministic metadata generated by mock provider.',
        language: 'en',
        audience: 'general'
      };
    case 'summary':
      return {
        shortSummary: 'Deterministic short summary.',
        detailedSummary: 'Deterministic detailed summary generated for integration testing.'
      };
    case 'keywords':
      return {
        keywords: ['deterministic', 'transcript', 'pipeline']
      };
    case 'scripture':
      return {
        references: [
          {
            book: 'John',
            chapter: 3,
            verseStart: 16,
            verseEnd: 17
          }
        ]
      };
    case 'reflections':
      return {
        reflections: [
          'Deterministic reflection point one.',
          'Deterministic reflection point two.'
        ]
      };
    default:
      return {
        message: 'Unsupported prompt key for mock provider.'
      };
  }
}

export class MockAIProvider implements AIProvider {
  public readonly providerName = 'mock' as const;

  public constructor(
    private readonly dependencies: MockProviderDependencies
  ) {}

  public async generate<TSchema extends z.ZodTypeAny>(
    request: AIRequest<TSchema>,
    signal: AbortSignal
  ): Promise<AIProviderResult<z.infer<TSchema>>> {
    if (signal.aborted) {
      throw new WorkerCancelledError('Mock provider request was aborted.');
    }

    if (this.dependencies.mode === 'timeout') {
      throw new AITimeoutError('Mock provider timeout mode is active.');
    }

    if (this.dependencies.mode === 'retryable-failure') {
      throw new AIProviderUnavailableError('Mock provider retryable failure mode is active.');
    }

    if (this.dependencies.mode === 'permanent-failure') {
      throw new AIPermanentError('Mock provider permanent failure mode is active.');
    }

    const payload = this.dependencies.mode === 'malformed-output'
      ? { malformed: true }
      : buildMockPayload(request.promptKey);

    const parsed = request.schema.safeParse(payload);

    if (!parsed.success) {
      throw new AIValidationError('Mock provider returned invalid output.', {
        promptKey: request.promptKey,
        issues: parsed.error.issues
      });
    }

    return {
      provider: this.providerName,
      model: request.model,
      output: parsed.data,
      usage: deterministicUsage(request.prompt),
      generatedAt: this.dependencies.now().toISOString()
    };
  }
}
