export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_JSON: 'INVALID_JSON',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  TENANT_CONTEXT_REQUIRED: 'TENANT_CONTEXT_REQUIRED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  INVALID_WORKFLOW_STATE: 'INVALID_WORKFLOW_STATE',
  JOB_NOT_CLAIMABLE: 'JOB_NOT_CLAIMABLE',
  JOB_ALREADY_COMPLETED: 'JOB_ALREADY_COMPLETED',
  TRANSCRIPT_HASH_MISMATCH: 'TRANSCRIPT_HASH_MISMATCH'
} as const;

export type ErrorCodeValue =
  (typeof ErrorCode)[keyof typeof ErrorCode];
